/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/common';
class Ng2BreadcrumbModuleInjector extends import0.ɵNgModuleInjector<import1.Ng2BreadcrumbModule> {
  _CommonModule_0:import2.CommonModule;
  _Ng2BreadcrumbModule_1:import1.Ng2BreadcrumbModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.Ng2BreadcrumbModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._Ng2BreadcrumbModule_1 = new import1.Ng2BreadcrumbModule();
    return this._Ng2BreadcrumbModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.Ng2BreadcrumbModule)) { return this._Ng2BreadcrumbModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2BreadcrumbModuleNgFactory:import0.NgModuleFactory<import1.Ng2BreadcrumbModule> = new import0.NgModuleFactory<any>(Ng2BreadcrumbModuleInjector,import1.Ng2BreadcrumbModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V2YW5qbWcvRGVza3RvcC9kZXZlbG9wbWVudC9qb2IvdmVsb2NpdHkvbmcyLWJyZWFkY3J1bWIvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXZhbmptZy9EZXNrdG9wL2RldmVsb3BtZW50L2pvYi92ZWxvY2l0eS9uZzItYnJlYWRjcnVtYi9hcHAvYXBwLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
